### ISSUE TITLE
Create a login and signup page.

### ISSUE THREAD

**Issue by PrakharRathore123** [SarthakKeshari/Notezy-Notes-Maintainer-#3]
**Is your feature request related to a problem? Please describe.**
I am going to create a login page and signup page to create new user account.

**Describe the solution you'd like**
I am going to use HTML,CSS,JS,BOOTSTRAP to create login page and signup page .

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Young-Tran** [comment]
hey can i tackle this issue?

**Comment by SarthakKeshari** [comment]
@Dungtran713 The project is not open for open source contribution yet.
